### PR TITLE
Enable certificate verification to prevent MitM

### PR DESCRIPTION
**Pull request by Dukecz**
## Motivation and context

I don't think it is a good idea to completely turn off cert verification as default behavior in regards to security.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](../docs/CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by tomas-novotny** [comment]
SSL verification for the API server was disabled with this [commit](https://github.com/inspirum/balikobot-php/commit/a1acf8286a97ee1736e5c35af0f4128b83d999eb#diff-eaf8aef3b9a3cf7b295e7eaeae6a59ff83335efb9b1c721e4be52ea8b34d2842) because Balikobot had an invalid certificate several times in the past, making it impossible to work with the API.

For our clients it is important that they can work with packages, and labels all the time, so Requester does not validate SSL rather than not working in these situations.

I don't know if these problem still happens nowdays.

So I suggest this changes: 

- add additional parameter to Requester constructor - something like `sslVerify`
- add condition to validate SSL only if this parameter is `true`
- for now, default value should be `false`
- in next major version (6.0.0) it will be switch to `true`

With this, no backward compatibility break will be introduce, and users will have simple option to force SSL verification.

Do you agree with these changes?

**Comment by Dukecz** [comment]
Yeah that would work too. I will update the PR.

I think the README should also be updated to mention that the verification is disabled by default as I would not expect such behavior.

**Comment by tomas-novotny** [comment]
I pushed changes as suggested in commit [ee7b670](https://github.com/inspirum/balikobot-php/commit/ee7b6705456edc3a9ce8891363707b137b0e7bf9). It will be soon released in new tag.

**Comment by tomas-novotny** [comment]
Changes was released in [v5.6.0](https://github.com/inspirum/balikobot-php/releases/tag/v5.6.0).

Future changes prepared in branch for tag [v6.0.0](https://github.com/inspirum/balikobot-php/commit/74371858171006839ee0b2c5818e1a575a16d6b3).

**Pull request closed without merging**
